### PR TITLE
index and about page descriptions

### PR DESCRIPTION
**Pull request by eplatte**
I've added descriptions to the index page (a very short introduction to the project) and the about page (a few changes to the longer paragraph from Carrie as well as a list of participants). Let me know if you want more information/different formatting.

### CODE REVIEW

**Comment by somiyagawa** [comment]
Thanks for the description!!

**Comment by somiyagawa** [comment]
Oops, it has a conflict.

**Comment by eplatte** [comment]
I've now created new pages for partners and for products. I've added a short description of Coptic SCRIPTORIUM to the partner page; other partners can add descriptions (links to all partner projects are in but can be updated if desired). I've added all the tools/products Carrie listed in issue 3 to the products page, with descriptions and links. Partner projects should also review and change if necessary. The formatting doesn't look great to me. So, can you please review the formatting and let me know what you think? Please feel free to change if you'd like, or I can make changes you suggest.

**Review by somiyagawa — APPROVED** [review]
Great! Thanks

**Pull request closed without merging**
